language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/soil-watch.ino

install:
    - pip install -U platformio
    - cp src/env.h.example src/env.h

script:
    - platformio ci --lib="src/env.h" --project-conf=platformio.ini

